# name: Playwright API Tests
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v4
#       with:
#         node-version: lts/*
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps
#     - name: Run Playwright tests
#       run: npx playwright test
#     - uses: actions/upload-artifact@v4
      # if: ${{ !cancelled() }}
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30

name: Running API tests with Playwright

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22, 23]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npx playwright install

      - name: Run API tests
        run: npm run test:api
      
      - name: Generate Allure Report
        run: npm run allure:generate
        continue-on-error: true
      
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_number }}
          path: allure-report

      - name: Cache Allure Results
        uses: actions/cache@v3
        with:
          path: allure-report/allure-results
          key: ${{ runner.os }}-allure-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-allure-